### ISSUE TITLE
Consolegrid never works

### ISSUE THREAD

**Issue by RNabuco** [scottrice/Ice#247]
Hello!

Right now, console grid never worked to download game images using ICE.

Also, is there a way to make ICE load custom icons and custom steam grid images?

Thank you :) And congratulations, ice is wonderful

**Comment by scottrice** [comment]
Would you post your consoles.txt? There is a bug right now where having an odd entry for 'nickname' will cause it to not download images at all.

As for the icons and grid images, Ice will do it automatically. Images should happen after we figure out your issue here, and we can set up icons after that

**Comment by RNabuco** [comment]
Of course! Here it is, thank you kindly!

[Nintendo Entertainment System]
nickname=NES
emulator=

[Super Nintendo]
nickname=Super Nintendo
emulator=

[Nintendo 64]
nickname=N64
emulator=

[Nintendo Gamecube]
nickname=Gamecube
emulator=

[Nintendo Wii]
nickname=Wii
emulator=

[Playstation 1]
nickname=Playstation
emulator=ePSXe

[Playstation 2]
nickname=Playstation 2
emulator=pcsx2-r5875

[PSP]
nickname=PSP
emulator=PPSSPP

[Sega Genesis]
nickname=Genesis
emulator=

[Sega Dreamcast]
nickname=Dreamcast
emulator=

[Nintendo Gameboy]
nickname=Gameboy
emulator=

[Gameboy Advance]
nickname=GBA
emulator=

[Nintendo DS]
nickname=DS
emulator=

**Comment by scottrice** [comment]
Try changing the nickname of Playstation to "PS1" and of Playstation 2 to "PS2"

If you go to ConsoleGrid there is a dropdown of consoles and they should have a nickname in parenthesis. You want your consoles nickname to match the equivalent on ConsoleGrid.

**Comment by RNabuco** [comment]
Oh yeah! It Works now! Thank you :D Now for the icons?

**Comment by scottrice** [comment]
Ah, so Ice currently has pretty basic icon support. It doesn't go and find special icons for every game in the same way it does grid images (mainly because there isn't nearly as much artwork out there for game specific icons and its pretty low visibility), but it does let you set custom icons for games of a given console. So all of your Gamecube games would have the same icon, all of your SNES games would have the same icon, etc.

To do that, there is actually just a field in consoles.txt that you can use. Just set

    icon=C:\path\to\icon.png

For the console you want and run Ice again.

**Comment by RNabuco** [comment]
Thanks a million, Mr Scott! 

Keep up this awesome work, you make classic golden games shine again with Ice!

Keep on chilling! I´m your fan! :D
