### ISSUE TITLE
Can't make custom icons work

### ISSUE THREAD

**Issue by imkrut** [scottrice/Ice#257]
Sorry if this has been adressed before, i've read and tried this multiple times but no luck.

I was even banking on/waiting on the reply to this issue (https://github.com/scottrice/Ice/issues/247) but the person there apparently had no problems getting it to work.

This is how it looks in the consoles.txt file 

[Super Nintendo]
nickname=SNES
emulator=retroarch_snes
extensions=smc
icon=C:\Emulators\Ice\Icons\icon.png

And i've tried several icon files (png) with different resolutions, but to no avail, all i get is the default Emulator icon from the executable.

I've tried at different times, and have redownloaded ICE on multiple ocasions thinking it might be a different version or something, but no luck, i also think i had the same problem with custom grid images loaded w/same file name (not loading) but it's been a while since i tried it.

Any help would be aprecciated.

**Comment by imkrut** [comment]
Upon further checking i can't make the following commands to work:

roms directory=X:\Folder
icon=X:\Folder\icon.png
images directory=X:\Folder\Images


Any help would be great.

**Comment by scottrice** [comment]
Thanks for the report. I'll try to take a look soon.

**Comment by imkrut** [comment]
Thank you, on a different, but related note, i've amassed a huge amount of custom made Steam banners (they look pretty good together since they are done all in the same way), uploading them 1 by 1 to console grid is really a pain, but i'd be happy to share them if an easier way to upload a "cover pack".

**Comment by scottrice** [comment]
Cover packs are definitely something that Ice wants to support (I added a field for consoles where you could define a directory with images in it and it would use those instead of hitting ConsoleGrid). Adding cover packs to ConsoleGrid itself is a really good idea, would you mind adding that as an issue to the ConsoleGrid GitHub page? I'm hoping to improve that in the near future as well.

**Comment by imkrut** [comment]
Sure thing, will do.

Really looking forward to any sort of help to the icons/image directory/rom directory issue, i can't for the life of me figure out if i'm doing something wrong or the feature broke somewhere.

Thanks in advance

**Comment by scottrice** [comment]
Oh wait, I think I might know your issue. Are you running from the source, or from the executable on the downloads page (aka `Ice.exe`)? The source code should have that feature while the executable won't. Unfortunately the executable on the downloads page is extremely old, as I was without a Windows computer to build Ice on for a while. Now that I have one and have stabilized Ice a bit I am hoping to release another version of the executable soon.

**Comment by imkrut** [comment]
The latter, i'm running from Ice.exe 

Guess I'll have to look into compiling it, I honestly don't have a clue where to begin tho.

Thanks for the help Scott.

**Comment by scottrice** [comment]
You shouldn't need to compile it, just run it. You can do it with `python src/ice.py`.

You will need to run `python setup.py install` first though, and unfortunately there is a bug right now that means you need to have py2exe installed if you want to run that command on Windows. I'm working on fixing it, but it will take me a while. So that leaves three options:

1) Install py2exe. This will let you run `python setup.py install` without a problem and you can run Ice.
2) Wait for me to fix the py2exe bug, which will let you run the source.
3) Wait for me to make another executable.

Those are basically in order of how quickly they will happen too. 1 you can do yourself ([download link](http://sourceforge.net/projects/py2exe/files/py2exe/0.6.9/py2exe-0.6.9.win32-py2.7.exe/download)), 2 and 3 should happen in a week or so.

Since we found the source of your icon problems I am going to close this issue to remove it from the open list, but feel free to comment if things still aren't working for you.

**Comment by imkrut** [comment]
I did all of the above, Ice starts, it detects both the console.txt configuration and the emulator.txt config,  then gets stuck on "User"
![python_ice](https://cloud.githubusercontent.com/assets/10028924/6071647/0cb71468-ad77-11e4-94e5-d917fb412b6e.png)

**Comment by imkrut** [comment]
Hey scott, did you ever get a chance to get around option 3?

 "3) Wait for me to make another executable."

Thanks!

**Comment by gwokk** [comment]
_Hey scott, did you ever get a chance to get around option 3?

"3) Wait for me to make another executable."

Thanks!_

I'm wondering this also - I think the ice.exe from the main downloads page is an older version which doesn't allow for image/icon directory

Cheers!
