### ISSUE TITLE
Cannot run at first time; Tasklist error

### ISSUE THREAD

**Issue by Mazerwulf** [scottrice/Ice#259]
I'm really trying to get this ICE thing working, but it refuses to run the first time, giving me the exact same error as seen here https://gist.github.com/HeroCC/fe2a804568685a824d93

I see that the dependency was supposedly removed but I still don't see how to solve this problem as it is still happening. What steps are needed to run this properly?

Currently using Windows 8 64bit if that helps and ICE version :Built at 10:39AM on October 31, 2013

Revision c5c1401

Please help :(

**Comment by Mazerwulf** [comment]
Windows 7. My mistake

**Comment by bgehrlein** [comment]
Is Steam closed fully prior to running?

**Comment by Mazerwulf** [comment]
Yessir. I checked task manager and everything is closed. I checked the services also and it said "not running" under there also.

**Comment by scottrice** [comment]
The version on the main site relies on Tasklist, which I found out later doesnt necessarily come on all Windows machines. I have no idea in what situations tasklist doesnt exist, but either way the fix is to use a more recent version of Ice (in which I remove that dependency). At time of writing, that means downloading the source code.

If you download the source you can find instructions on how to run it on the main page (it should just be running `python setup.py install` and then `python src/ice.py`). Otherwise I am hoping to have a new version of the executable up on the site in the next week or so. Just need to do some more testing before I release it into the wild.

**Comment by Mazerwulf** [comment]
Thank you very much! I will try your suggestion and good luck on the new executable!

The tasklist thing is really strange. It seems I even have it on my PC but it just isn't recognized by the program - that or I am just not looking at things properly...but anywho, good luck!

**Comment by Denzu** [comment]
This can also happen if tasklist isn't in your system PATH. Same thing happened to me.

**Comment by scottrice** [comment]
I no longer use tasklist, so this issue is effectively completed.
