### ISSUE TITLE
Regarding Issue #257, new "executable" version of the phyton

### ISSUE THREAD

**Issue by imkrut** [scottrice/Ice#292]
In regards to this issue, I've been waiting for a few months to see if there's a new exec.
https://github.com/scottrice/Ice/issues/257#issuecomment-73151900

I have a phyton shortcut and it takes quite some time to add the shortcuts to steam in comparison to the non-python version, was wondering if there's a way around this now, 

Also wondering if my last suggestion on the last issue is feasable (auto backdrop image add)

thanks in advance!

**Comment by scottrice** [comment]
For a while I was putting off making a new executable because of an issue that would cause duplicate games to show up if the user switched from old executable version directly to the newest version. I couldnt release a new version under that state, so I put it off.

That issue was fixed very recently, so I will try to put up a new version soon. Things have been crazy for me recently, so it may take a while. Sorry for the delays, and thanks for the patience.

**Comment by imkrut** [comment]
Awesome, looking forward to it, hopefully you can update it here with a msg so I know right away!

**Comment by imkrut** [comment]
Hi Scott, sorry to bother you, but has there been any news up in the update front?

Thank you.

**Comment by scottrice** [comment]
Unfortunately not, the last month has been super crazy for me. Things are winding down though, so I'll try to get this taken care of soon.

**Comment by lufykun** [comment]
hello 
have you some new about the new executable ?

**Comment by nileplumb** [comment]
checking in for news

**Comment by scottrice** [comment]
Just built a new version - https://github.com/scottrice/Ice/releases/download/1.0.0/Ice.zip
