### ISSUE TITLE
Still trouble building Ice properly with Ubuntu 14.04

### ISSUE THREAD

**Issue by futurepr0n** [scottrice/Ice#355]
@scottrice  I tried to go through the process of running ice again from the latest, but am still getting the same issue with the backups directory. Which is odd considering I tried taking that section out completely from the config.txt

futurepr0n@futureMedia:~/Ice$ sudo python -m ice
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/futurepr0n/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
warnings.warn(msg, UserWarning)
=========== Starting Ice ===========
Detected Emulator: Dolphin
Detected Emulator: PCSX2
Detected Console: Nintendo Gamecube => Dolphin
Detected Console: Playstation 2 => PCSX2
=========== User: 2267067 ===========
[ERROR] An exception occurred while running Ice
Traceback (most recent call last):
File "ice/runners/ice_engine.py", line 154, in run
self.main(dry_run=dry_run)
File "ice/runners/ice_engine.py", line 134, in main
self.run_for_user(user_context, dry_run=dry_run)
File "ice/runners/ice_engine.py", line 146, in run_for_user
self._create_backup(user, dry_run=dry_run)
File "ice/runners/ice_engine.py", line 164, in _create_backup
shortcuts.write_shortcuts(backup_path, shortcuts.get_shortcuts(user))
File "/usr/local/lib/python2.7/dist-packages/pysteam-1.0.0_beta1-py2.7.egg/pysteam/shortcuts.py", line 31, in write_shortcuts
with open(path, "w") as f:
IOError: [Errno 2] No such file or directory: '/home/futurepr0n/.config/ice/Backups/2267067/config/shortcuts.20160125174051.vdf'

Close the window, or hit enter to exit...

The good news is - that I see the Dolphin Emulator and PCSX 2 in Steam - but I dont see the games, so I guess it never gets far enough to add those into my Steam.

**Comment by scottrice** [comment]
@futurepr0n - I don't think you're actually running the latest code. I see in your stack trace that the `write_shortcuts` method is being called from `ice_engine.py`. That particular bit of code was moved from `ice_engine` to `backups.py` around 2 weeks ago specifically so that I could test and fix the situation you describe. You can see the relevant line of code here - https://github.com/scottrice/Ice/blob/master/ice/backups.py#L65.

Anyway, I'm pretty sure this problem is fixed already so I'm going to close this issue. If you are still having problems after downloading the latest master then please reopen this issue (using the button below) and I can help you out.

**Comment by futurepr0n** [comment]
Thank you! It looks like I was retrying with an old build and as you were kind enough to reply, I was able to download the latest and run with no issues! Thank you so much for your work on this!
